### ISSUE TITLE
Nachrichten: konstantes design

### ISSUE THREAD

**Issue by CodeSpoof** [alessioC42/lanis-mobile#119]
Bei ungelesenen Nachrichten sorgt das Glockensymbol dafür, dass die Nachricht nach rechts verschoben wird und die Vorschau dadurch nicht in das Bild der restlichen Nachrichten passt. Vllt. durch einen Benachrichtigungspunkt ersetzen?

**Comment by kurwjan** [comment]
Ja man könnte es ersetzten, aber ich weiß nicht ob es so schlimm ist, wenn es verschoben wird, die ganze Vorschau passt bei längeren Titeln eh nicht rein.

**Comment by kurwjan** [comment]
äh ja da hat sich wohl was verändert

**Comment by kurwjan** [comment]
äh ja da hat sich wohl was verändert
