### ISSUE TITLE
Mein Unterricht sotieren

### ISSUE THREAD

**Issue by baum-eule** [alessioC42/lanis-mobile#127]
### Idee

Wäre es möglich die Einträge bei Aktuelles nach ihrem alter zu sortieren und oder die Einträge ausblenden, die keine Daten besitzten?

**Comment by alessioC42** [comment]
Das mit dem Sortieren geht auf jeden Fall. Das mit dem Ausblenden muss ich mir noch ansehen. Kannst du in der Anwendung einen internen Fehlerbericht mit Metadaten an schicken? Dann kann ich deine Situation nachvollziehen und es entsprechend ausblenden. Schreibe einfach irgendwas in die Textfelder.

**Comment by baum-eule** [comment]
Ich habe den Bericht geschrieben. Das Problem mit den Leeren Einträgen wurde schonmal behoben. #70

**Comment by alessioC42** [comment]
Das ist ja Witzig, wenn ich mir deine Daten so ansehe...
kann es sein, dass bei einigen Kursen gar keine Tage dabeistehen?

**Comment by baum-eule** [comment]
Gibt eine Möglichkeit sie auszublenden?

**Comment by alessioC42** [comment]
Ja, ich bin gerade dabei es zur Implementieren
