### ISSUE TITLE
Text-Formatierungsfehler

### ISSUE THREAD

**Issue by baum-eule** [alessioC42/lanis-mobile#128]
Es gibt bei der Text Formatierung in den Nachrichten Fehler

Das durchstreichen von Text wird nicht angezeigt.
Bei der Uhrzeit werden die Minuten nicht geschrieben.
Wenn Zahlen verschoben werden sollen, werden sie nicht verschoben.

Schulportal Webseite:
![image](https://github.com/alessioC42/lanis-mobile/assets/130868748/bfaf1575-8373-4dae-9561-3ecabe6cacc8)

App:
![image](https://github.com/alessioC42/lanis-mobile/assets/130868748/08376259-bf97-4cf6-ae0d-fe96e5cc296f)

Text:
```
unterstrichen wird zu _unterstrichen_
entfernt wird zu --entfernt--
- Aufzählung 1
- Aufzählung 2
- Aufzählung 3
Quellcode wird zu Quellcode
Datum v1  12.04.2018 
Datum v1  12.04.18
Datum v2  (12.04.2018) 
Datum v2  (12.04.18)
Uhrzeitenangabe 11:13
Link https://example.com/
Linkkürzung https://example.com/abcdefghijklmnopqrstuvwxyz_abcdefghijklmnopqrstuvwxyz_abcdefghijklmnopqrstuvwxyz
Email test@example.com
Zahl sonderfall v1 _1
Zahl sonderfall v1 _(1)
Zahlen sonderfall v1 _(123)
Zahl sonderfall v2 ^1
Zahl sonderfall v2 ^(1)
Zahlen sonderfall v2 ^(123)
```

**Comment by baum-eule** [comment]
Habe grade noch einen ähnlichen Fehler bei einem Kalender Eintrag gefunden.
Schulportal:
![image](https://github.com/alessioC42/lanis-mobile/assets/130868748/e1aa361b-8ae8-4184-9d0f-661348bb260d)

App:
![image](https://github.com/alessioC42/lanis-mobile/assets/130868748/f3355c41-45e2-47f2-aac3-7551c350a99c)

Andere Einträge sind aber Richtig:
![image](https://github.com/alessioC42/lanis-mobile/assets/130868748/e4e3666a-c681-472a-aa39-0a41c27f9a9d)

**Comment by alessioC42** [comment]
&amp; ist ein "&"

Es gibt ein paar solcher Codes in HTML
https://www.rapidtables.com/web/html/html-codes.html

**Comment by kurwjan** [comment]
Eine einzelne Zahl wird nur mit `_ZAHL ` _(und einem Leerzeichen danach)_ zu Super- oder Subscript, so wie es in den Docs vom Schulportal steht.
Sonst kann man `_(ZAHLEN)` benutzen _(ohne Leerzeichen)_.

Das durchstreichen und kursiv muss man beheben, funktioniert anscheinend irgendwie nicht mehr.
Und das mit Uhrzeiten dachte ich hätte es mal behoben, ist wohl untergegangen.

**Comment by kurwjan** [comment]
```dart
FormatPattern(
          regExp: RegExp(r"(\d{2}:\d{2} Uhr)|(\d{2}:\d{2})", caseSensitive: false),
          startTag: "<time>",
          endTag: "</time>"
      ),
```
Das wäre ein möglicher Fix für die Uhrzeit
