### ISSUE TITLE
Halbjahr

### ISSUE THREAD

**Issue by baum-eule** [alessioC42/lanis-mobile#131]
Im Schulportal wird zwischen dem ersten Halbjahr und dem zweitem Halbjahr unterschieden. Deswegen sieht man, wenn das zweite Halbjahr begonnen hat, nur neue Einträge die im neuem Halbjahr passiert sind. 
Um alte Einträge von einem Fach zu sehen, wird man auch einen Knopf drücken müssen, der dort sein wird wo jetzt 1. Halbjahr steht.
Dies ist letztes Schuljahr auch so gewesen, weswegen ich schätzte, dass es dieses mal auch so sein wird.

Man kann es jetzt schon testen mit den richtigen URL Parametern.
Beispiel URL: https://start.schulportal.hessen.de/meinunterricht.php?a=sus_view&id=1234&halb=2 

Es wäre nützlich, wenn man im zweitem Halbjahr auch die Einträge aus dem erstem Halbjahr einsehen kann.
(Es bezieht sich meines Wissens nach nur auf die Fächer Ansicht und nicht auf die Übersicht)

**Comment by alessioC42** [comment]
Das habe ich auch schon gesehen. Ich muss sagen, ich weiß nicht mehr, was ich dann gemacht habe, aber ich weiß, dass die Elemente noch da waren und dass es nur ein "hidden" in dem entsprechenden HTML-Tag war. Wenn es also Probleme gibt, sollte es einen schnellen Fix geben, um das zu beheben.

**Comment by alessioC42** [comment]
Ich kümmere mich heute drum. Jetzt ist das HTML dazu auch da.
