### ISSUE TITLE
Network not available

### ISSUE THREAD

**Issue by alessioC42** [alessioC42/lanis-mobile#143]
https://lanis-mobile.duckdns.org/dashboard#/659c667be9bd1eab79ee33e0/crashes/93d157eb956eb86793799c278e4f4f92d303f140

https://lanis-mobile.duckdns.org/dashboard#/659c667be9bd1eab79ee33e0/crashes/2e18c14a7699a3321c7d3a942f8e7c61eabe7226

https://lanis-mobile.duckdns.org/dashboard#/659c667be9bd1eab79ee33e0/crashes/74e826f62be129d1380ca0dc6a0530e78bfc451f

Ich bin mir ziemlich sicher, dass sie durch #126 gekommen sind. In #126 sollte geprüft werden, ob der Benutzer online ist, bevor eine Anfrage gestellt wird.

**Comment by CodeSpoof** [comment]
Ich habe verschiedene Szenarien durchprobiert, aber der Fehler trat nicht auf, wenn ich nach Anmeldung das Internet gekappt habe. Er trat auf, als ich den Bildschirm aus bzw. die App im Hintergrund hatte. Es könnte sich auch um Hintergrundbeschränkungen von Android handeln. Es handelt sich bei der Fehlermeldung auch nicht um einen Verbindungsabbruch, sondern um ein Timeout. Bei mir scheint der Fehler auch schon aufgetreten zu sein, aber mitbekommen habe ich davon nicht wirklich etwas.

**Comment by alessioC42** [comment]
Okay, dann könnte man den Fehler wenigstens mit einem "try-catch" abfangen, damit er Countly nicht zuspammt.

**Comment by CodeSpoof** [comment]
Ich weiß halt nicht genau wo er auftritt. Immer nur im Hintergrund und der Stacktrace sagt nichts genaueres.

**Comment by alessioC42** [comment]
Kann es nicht nur die Request sein? 
Die Fehler sollten doch alle in dio.post passieren?
