### ISSUE TITLE
code cleanup

### ISSUE THREAD

**Issue by alessioC42** [alessioC42/lanis-mobile#151]

**Comment by CodeSpoof** [comment]
Ich mache ein paar Sachen grade was die Modul-Unterstützungs-Erkennung angeht

**Comment by alessioC42** [comment]
Dann mache ich es danach

**Comment by kurwjan** [comment]
Im Code könnte man auch docstrings (`///`) hinzufügen damit es halt bisschen dokumetierter ist.
