### ISSUE TITLE
Vertretugsplan Filter anhand von Klasse bestimmen

### ISSUE THREAD

**Issue by alessioC42** [alessioC42/lanis-mobile#156]
Es kann mit Heuristiken der filter für eine menge Nutzer automatisch gesetzt werden. 
Eg. 7a -> 7 und a

https://github.com/alessioC42/lanis-mobile-autoconfig/

**Comment by CodeSpoof** [comment]
Würde ich aufpassen mit. Bei uns in der Oberstufe steht da manchmal `ObSt.` und manchmal `Q1/Q2` / `Q3/Q4` / `E` oder auch 13A etc. Jenachdem wer alles gemeint ist.

**Comment by alessioC42** [comment]
Ja, bei uns auch. Desshalb erstmal auch nur Heuristik. Es ist in erster linie so gedacht, dass neuere Nutzer automatisch den richtigen Filter haben. (meine Klasse heißt: "q1hpkr")

Ich habe auch darüber nachgedacht das extern zu berechnen. In der idee hätte man eine Edge Funktion (Coudflare Worker/Amazon lambda etc) die es dir passend bestimmt. Dann könnten Schulspezifische dinge ohne ein App-Update festgelegt werden.

Ist erstmal nur ne idee.
