### ISSUE TITLE
Verbindungscheck schlägt fehl trotz Erreichbarkeit des SPH

### ISSUE THREAD

**Issue by CodeSpoof** [alessioC42/lanis-mobile#158]
Rückmeldung beim Anmelden: Keine Verbindung

**Comment by alessioC42** [comment]
Wie?
Im prod build oder mit den neuen exeptions? Wie darf man das verstehen?

**Comment by CodeSpoof** [comment]
Prod build. Unser WLAN in der Schule hat einen Filter, der das SPH zulässt, aber der Verbindungscheck wird wohl geblockt.

**Comment by alessioC42** [comment]
Das kann behoben werden, indem anstelle populärer DNS Server das Schulportal gepingt wird. Dann würde auch bei einer Downtime des SPH die App nicht Funktionieren.

https://pub.dev/packages/internet_connection_checker#default_addresses
