### ISSUE TITLE
Fehlerberichte nicht sendbar

### ISSUE THREAD

**Issue by CodeSpoof** [alessioC42/lanis-mobile#163]
Fehlerberichte werden nicht gesendet

**Comment by alessioC42** [comment]
Ich werde in nächster zeit versuchen fehlerberichte auch auf Countly zu schieben. Da gibt es ja den "Feedback" tab über den das gehen sollte

**Comment by alessioC42** [comment]
Fehlerberichte sind jetzt eh raus
