### ISSUE TITLE
Question on permissions and signing details

### ISSUE THREAD

**Issue by IzzySoft** [alessioC42/lanis-mobile#180]
My [recently enhanced scanner](https://gitlab.com/IzzyOnDroid/repo/-/issues/475) just reported on yesterday's update of your app:

```
! repo/io.github.alessioc42.sph_25.apk declares sensitive permission(s): android.permission.READ_EXTERNAL_STORAGE
! repo/io.github.alessioc42.sph_25.apk contains signature block blobs: 0x6dff800d (SOURCE_STAMP_V2_BLOCK; GOOGLE)
```

Could you please clarify what the storage permission is needed/used for? And how this Google blob comes into your signing block (I always thought only Google themselves are adding this one, or at least that this only goes for AABs)? Some details on those "signing block blobs" are outlined behind above links, a short summary can be [found here](https://apt.izzysoft.de/fdroid/index/info#signingblock).

While being here, this one nags me for quite a while now:

```
io.github.alessioc42.sph: failed to retrieve commits for 'datenschutzerklärung.txt' on spec '' - cannot set ts/date
```

Looks like Github's API cannot deal with "umlauts". Not really an issue but rather a minor annoyance – but if you could maybe rename that file to e.g. `datenschutzerklaerung.txt` to get rid of that warning I'd really appreciate that. Thanks!

**Comment by alessioC42** [comment]
Permission is required to upload files to SPH (#110)

The APK that I upload to GH releases is signed by Google. I upload the AAB to the Play Console and download the universally signed APK to make it available on the releases. I chose this to make sure there is no "untrusted developer" alert when installing the APK. 
I could also provide an APK signed only with my keystore.

The `datenschutzerklärung.txt` file is outdated anyway. It seems that git did not remotely delete it. We changed it to the `SECURITY.md` file to include it right next to our readme on the repository main page.
So you might want to change this to https://raw.githubusercontent.com/alessioC42/lanis-mobile/main/SECURITY.md

**Comment by IzzySoft** [comment]
> I chose this to make sure there is no "untrusted developer" alert when installing the APK.

Ah, I've heard of such popups. Been told that "Play Protect" does such things. And you're "untrusted" if you don't trust Google. They're quite successful with this trick to bind devs to their ecosystem, yeah…

> I could also provide an APK signed only with my keystore.

Would probably be a good idea, who knows what "fun" Google comes up with next. It's the same key (certificate) I guess (so no "breaking change" causing the need to uninstall and reinstall)? Then I'd say I'd go for that. If you want to provide both at your releases, just let me know the "naming convention" chosen and I teach my updater accordingly.

> The `datenschutzerklärung.txt` file is outdated anyway.

Ah, so it could be removed? It's not that I try to access/download it, it's just encountered when parsing the "root" to see if there's a [`FUNDING.yml`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository) (which should be located either in `.github/` or directly in the repo root – if it shall be found that is).

**Comment by alessioC42** [comment]
> It's the same key (certificate) I guess (so no \"breaking change\" causing the need to uninstall and reinstall)?

Sadly that's not the case. I am like 99% sure, that a reinstallation is reqired to update to a non-google signed build. I will test this soon, but i am pretty sure that it won't work. I had the same behavior when i updated to google signing in v2.5.0+3

**Comment by alessioC42** [comment]
> It's the same key (certificate) I guess (so no "breaking change" causing the need to uninstall and reinstall)?

![Screenshot_20240216-192805_Package installer](https://github.com/alessioC42/lanis-mobile/assets/84250128/76fcb35e-fdb7-41d7-9692-ded75c8c2fc7)

Yeah, that just doesn't work. 

We are working on a big update anyway (#169 and mb Apple App Store) and would consider a new major release. Do you need a major release to stop things from breaking? Although these are big updates, they are more like minor changes to the core application. 

I will call the non-Google build `app-release-selfsigned.apk`.

**Comment by IzzySoft** [comment]
> I am like 99% sure, that a reinstallation is reqired to update to a non-google signed build.

Did you let Google **create** that key – or did you give them a key of yours to sign with? In the latter case you could use that key you handed them. In the former case no dice, as they won't give you your own private key.

> Do you need a major release to stop things from breaking?

If uninstall and reinstall is needed anyhow, that makes no difference. I'd leave the timing to you then. Just let me know when I shall switch to the new naming. The new key will then announce itself (by an error message as it does not correspond to the one pinned here), and I'll then pint the new one. Name is fine, I'd match on `/selfsigned/i` then.

**Comment by alessioC42** [comment]
> Did you let Google **create** that key – or did you give them a key of yours to sign with? In the latter case you could use that key you handed them. In the former case no dice, as they won't give you your own private key.

Google created this key. As far as I know, this is standard procedure in the Google Play Store. 

![image](https://github.com/alessioC42/lanis-mobile/assets/84250128/454f3af3-5485-418f-9f8b-266604e552c2)


> Just let me know when I shall switch to the new naming

The next update will include the self-signed APK. I will ping you when it is online.

**Comment by IzzySoft** [comment]
> Google created this key. As far as I know, this is standard procedure in the Google Play Store.

I'm no Android dev, so I didn't follow how this proceeded. Originally, devs uploaded the APKs they signed. Then Google started insisting they do the signing. For that they offered you to create the key for you – or alternatively, you could upload yours (or a subkey of it, I don't remember the full details). But I wouldn't be surprised if they now forced you to use their key – so they have full control (and can modify as they see fit).

There's something with "upgrade your key" (cut off in your screenshot). Increasing "encryption key strength" would mean a new key. If you have minSdk at Android 9 or higher, they could handle that via key rotation (was introduced with Android 9, so lower versions don't support it). I don't know if they'd offer you to upload a key there – or if you'd have that option in the beginning (e.g. for a new app).

OK, whichever it is: I'll wait for your signal. And as Debian has it: It's ready when it's ready – so no pressure :wink:

**Comment by alessioC42** [comment]
The update is now available. 
You can find the file `app-release-selfsigned.apk` in the releases now.

**Comment by IzzySoft** [comment]
Woof, that crossed: the moment you've hit "comment" here, my updater had already grabbed the other APK – so that's out already. OK, I've adjusted it now, so it will kick in with the next release then, thanks!

**Comment by IzzySoft** [comment]
Replaced now, effective with the next sync then. Thanks!

PS: I've also added a changelog for that release stating people need to uninstall and reinstall. Should your next release come earlier than in 4 weeks, be welcome to send me a note to extend that to the newer version as well, for those who might have missed it before.
