### ISSUE TITLE
Falscher Benachrichtigungs-Text

### ISSUE THREAD

**Issue by CodeSpoof** [alessioC42/lanis-mobile#181]
![Screenshot_20240216-084520_Lanis.png](https://github.com/alessioC42/lanis-mobile/assets/42744253/3f7ac1d3-3ab1-4e41-97b6-595409592a0b)

![IMG_20240216_084511.jpg](https://github.com/alessioC42/lanis-mobile/assets/42744253/3383a0b9-16e7-4a73-b047-b417f32a38c0)

Der Tag ist falsch

**Comment by alessioC42** [comment]
Mach mal einen Fehler Bericht mit zusätzlichen infos an. Dann kann man das noch nach heute reproduzieren.

**Comment by CodeSpoof** [comment]
Hab nen Fehlerbericht gemacht
