### ISSUE TITLE
Nachrichten Lag

### ISSUE THREAD

**Issue by CodeSpoof** [alessioC42/lanis-mobile#183]
Wenn die Nachrichten geladen werden, gibt es nach kurzer Zeit einen mehrere Sekunden langen Hänger, in dem der Bildschirm nicht aktualisiert wird. Wenn man während die Nachrichten laden zu einem anderen Tab wechselt, passiert das gleiche. Also irgendein Code der im Main-Thread läuft und das nicht sollte.

**Comment by kurwjan** [comment]
Der ListView.builder und getConversationWidget haben halt paar if statements (oder ähnliches) aber ich glaube eher weniger das das Problem ist. Villt. hat es auch was mit der TabBarView zu tun?
Sonst dachte immer der Hänger wird vom ListView.builder erzeugt weil die Nachrichten halt instanziert werden.

**Comment by kurwjan** [comment]
Habe mir das mal genauer angeguckt.

Ich glaube der Lag kommt einfach nur von der massiven Nachrichten-Json (teilweise 1MB oder mehr), die wir herunterladen und decrypten müssen.

**Comment by alessioC42** [comment]
Nur ein paar Gedanken schule-5182 kann ja eh nicht Nachrichten benutzen.

Eigentlich sollte das nicht frezen, wenn das richtig implementiert wurde. Dart's async system funktioniert da. Vielleicht muss irgendwo stattdessen ein callback benutzt werden?

Wie lange ist denn der initial page load bei lanis?

**Comment by kurwjan** [comment]
Ich habe mal fehlende asyncs und awaits hinzugefügt, aber es hat sich leider gar nichts verändert.

Der Code sollte eigentlich richtig implementiert sein, hier ist die Problemstelle:
```dart
final response =
      await dio.post("https://start.schulportal.hessen.de/nachrichten.php",
          data: {
            "a": "headers",
            "getType": invisible ? "unvisibleOnly" : "visibleOnly",
            "last": "0"
          },
          options: Options(
            headers: {
              "Accept": "*/*",
              "Content-Type":
              "application/x-www-form-urlencoded; charset=UTF-8",
              "Sec-Fetch-Dest": "empty",
              "Sec-Fetch-Mode": "cors",
              "Sec-Fetch-Site": "same-origin",
              "X-Requested-With": "XMLHttpRequest",
            },
          ));

final Map<String, dynamic> encryptedJSON = jsonDecode(response.toString());

final String? decryptedConversations = client.cryptor.decryptString(encryptedJSON["rows"]);

if (decryptedConversations == null) {
        throw UnsaltedOrUnknownException();
}

return jsonDecode(decryptedConversations);
```
Der Rest (Fetcher, View und so) sollte fast exakt gleich funktionieren wie Mein Unterricht oder so. Nachrichten benutzt halt zwei Fetchers, weil beide Nachrichtenarten zusammen wären viel zu viel MB.

Bei Lanis gibt es halt extra diesen Ladebalken:
![image](https://github.com/alessioC42/lanis-mobile/assets/73837560/3899a4a7-a629-48b5-bf3e-7ec1a9d16ac2)

Außerdem ist es auch nicht immer ein vollständiger freeze, manchmal springt auf knapp unter 60 FPS und manchmal zu ca. 25FPS

**Comment by kurwjan** [comment]
Hab aber auch mal gelesen das Async bei "aufwendigeren" Aufgaben auch nicht so wirklich geeignet. Die (Albtraum-)Alternative wäre Threading.

Ich weiß jedoch nicht wie genau Dart's Async funktioniert.

**Comment by kurwjan** [comment]
Hab da wohl eine Lösung
