### ISSUE TITLE
Mehr Infos

### ISSUE THREAD

**Issue by tobfd** [alessioC42/lanis-mobile#189]
Ich hätte gerne bei jedem Eintrag im Vertretungsplan mehr Infos weil machnmal nur Französchich ausfällt auch wenn ich kein Französchich habe. Und das Fach steht da halt nicht.

**Comment by alessioC42** [comment]
Wie stellen alle Daten, die über die Schulportal Website abrufbar sind dar. Wenn einträge unvollständig sind, dann ist wahrscheinlich deine schule dafür verantwortlich. (Die würde dann bestimmte Felder nicht ausfüllen.

Für mich hört es sich auch danach an, dass der Filter nicht korrekt funktioniert. Bitte überprüfe die Einstellungen des Filters.

Wenn es nicht wie codespoof gesagt hat diese Informationen sind, kannst du bitte erklären, was mit "mehr Informationen" gemeint ist?

**Comment by alessioC42** [comment]
Hast du das Problem immernoch? @tobfd Sonnst würde ich das Issue schließen

**Comment by tobfd** [comment]
@alessioC42 Ja du kannst das Issue schliesen.
