### ISSUE TITLE
Vertretungsplan overflow bei zu vielen EInträgen

### ISSUE THREAD

**Issue by alessioC42** [alessioC42/lanis-mobile#193]
![image](https://github.com/alessioC42/lanis-mobile/assets/84250128/ce95d502-401f-4c69-a952-b6ba94e32d7f)
![image](https://github.com/alessioC42/lanis-mobile/assets/84250128/790063f9-db09-4ba2-ab97-1b798c4733e4)
(school-5181)

Ich würde einfach die Anzahl der Einträge limitieren, die da angezeigt werden können oder oben so eine Art scrollview draus machen. 

@CodeSpoof: Hier gibt es auch kein AJAX-Interface und alle Eingaben sind für den jeweiligen Account gültig. Ist das bei dir auch so? Dann könntest du den Filter deaktivieren, wenn es keine AJAX API gibt. (Macht zwar keinen Sinn, dass du dann etwas in lanis-mobile-autoconfig eingetragen hast, wollte aber nochmal nachfragen)

**Comment by CodeSpoof** [comment]
Stimmt zwar, dass die Einträge schon vorgefiltert sind, aber die Filter funktionieren für unsere Schule nicht vernünftig
