### ISSUE TITLE
Externe Logins

### ISSUE THREAD

**Issue by alessioC42** [alessioC42/lanis-mobile#195]
Es gibt im Schulportal für Schulen die Möglichkeit, eigene Anwendungen mit Login aus dem Schulportal zu unterstützen. Es sollte möglich sein, diese Logins direkt zu unterstützen. 
Sie zeichnen sich durch ihre URL `index.php?a=f&e=t78-1` aus. 

Ein erster Blick auf die Requests zeigt eigentlich einen relativ nachvollziehbaren Flow, nur der markierte Request könnte Probleme bereiten.
![image](https://github.com/alessioC42/lanis-mobile/assets/84250128/d347ef04-cf12-4589-b26d-b4265056fcaa)

**Comment by kurwjan** [comment]
Kann man dann diese Seiten im NavDrawer verlinken oder soll es eine neue Seite dafür geben?

**Comment by alessioC42** [comment]
Ich dachte an navdrawer. Eventuell müsste eine einstellung zum Anzeigen einzelner applets eingebaut werden.
Alternativ wäre ein submenü im navdrawer möglich.

**Comment by alessioC42** [comment]
Es ist aufgrund des SSO-Authflow einfach nicht möglich, den Benutzer in einem externen Browser anzumelden. Eine WebView wäre theoretisch innerhalb der Anwendung möglich, indem der Session-Cookie gesetzt wird, aber dieser Ansatz ist sehr unelegant und führt vor allem zu Fehlern durch Links innerhalb der Website.
