### ISSUE TITLE
Vertretungsplan-Filter für Kurs-Namen

### ISSUE THREAD

**Issue by CodeSpoof** [alessioC42/lanis-mobile#198]
Kursnamen sind bei einigen Schulen besser geeignet für das korrekte FIltern. Beispielsweise "MA L2" oder "SP G5".

**Comment by alessioC42** [comment]
Mit [dem neuen Filtersystem](https://github.com/alessioC42/lanis-mobile-autoconfig) müssen wir das Ganze glaube ich einmal zusammen von Anfang an neu machen. Ich denke es ist am besten, wenn man auf jedes Element einen Filter legen kann.

**Comment by Blitz08** [comment]
Bei meiner Schule (Johanne Gutenberg Schule Gernsheim) ändert sich nicht die Kurs bezeichnung sondern nur der Name der Lehrkraft.

**Comment by Blitz08** [comment]
![IMG-20220111-WA0000.jpg](https://github.com/alessioC42/lanis-mobile/assets/109095691/da8db0d9-5502-46b4-8c3a-4b68f8813257)
So sieht es bei uns aus.👆

**Comment by alessioC42** [comment]
>  So sieht es bei uns aus.👆

Was ich bei euch jetzt sehr interessant finde, ist, dass der Lehrer ~~durchgestrichen~~ gerendert wird. Wir haben ja schon viele Unterschiede im Vertretungsplan gesehen (Ajax, Non-Ajax etc.), aber das ist relativ neu. 

Aus meiner Sicht würde das keinen Sinn machen, aber vielleicht greift hier irgendwie das Custom Markup System des Schulportals. Jedenfalls sollten wir das im Hinterkopf behalten, falls es damit Filterprobleme geben sollte.

Inzwischen habe ich Zugang zu einem anderen Account von schule-5181 (dem wir den Datenspeicher und den Stundenplan zu verdanken haben). 

![Screenshot_20240423_213147](https://github.com/alessioC42/lanis-mobile/assets/84250128/517fa38f-6430-4881-adb2-ed0e63661940)

Man sieht vor allem, dass nicht alle Felder (hier Feld "Typ") gleich sind. → Jede Schule hat andere Felder. 🥲

Ergo muss das Filtersystem auch im Falle von @CodeSpoof und @Blitz08 auf jeden möglichen Parameter anwendbar sein.  Da der Ajax-Endpoint einen vollständigen Eintrag zurückgibt, sollte dies relativ einfach zu implementieren sein, sobald ich die Zeit finde. 

```ts
/**
 * interface to handle the vplan entries from the sph client (Lanis JSON response)
 */
interface SPHVplanEntry {
  Tag: string;
  Tag_en: string;
  Vertreter?: string;
  Lehrer?: string;
  Stunde: string;
  Klasse?: string;
  Klasse_alt?: string;
  Fach?: string;
  Fach_alt?: string;
  Raum?: string;
  Raum_alt?: string;
  Hinweis?: string;
  Art?: string;
  Hinweis2?: string;
  Lehrerkuerzel?: string;
  Vertreterkuerzel?: string;
  Lerngruppe?: never;
  _hervorgehoben: string[];
}
```
Ein filter müsste demnach letztlich ein array an regEx für jeden String sein.
