### ISSUE TITLE
Protecting app screen from prying apps (screenshots, recent apps)

### ISSUE THREAD

**Issue by serrq** [alessioC42/lanis-mobile#200]
![1000108037](https://github.com/alessioC42/lanis-mobile/assets/113377431/d12baeaa-1836-4a80-9b32-62b288cc1397)

![1000108069](https://github.com/alessioC42/lanis-mobile/assets/113377431/56ac561a-4972-4737-8ad8-add698d64e1c)

**Comment by alessioC42** [comment]
That's an interesting idea. Some parts of the application could benefit from this feature. (Mostly grades and sensitive information) Meanwhile, other parts of the application could not. For example my class often shares screenshots of the substitution plan in some group chats. 

I will enable this in some views with sensitive information, but most parts of the application benefit from the ability to take screenshots. 

It also looks like the [screen_protector](https://pub.dev/packages/screen_protector) package already has a working simple API for Android and the future IOS release.

**Comment by alessioC42** [comment]
Jeah. I guess a toggle should work. Will definitely be implemented.
I thought the screenshot with the toggle was just a fancy custom rom app menu item.

**Comment by alessioC42** [comment]
requires an Android SDK upgrade and is therefore not implemented.
