### ISSUE TITLE
Besserer Fehler-Ladescreen bei falschen Anmeldedaten

### ISSUE THREAD

**Issue by kurwjan** [alessioC42/lanis-mobile#204]
Anstatt immer "Beim Laden ist ein Fehler passiert!" zu zeigen, kann man den Fehler genauer zeigen und bei einem falschen Passwort, ein Passwort ändern Knopf hinzufügen. Außerdem wäre ein App-Zurücksetzen-Knopf gut.

**Comment by kurwjan** [comment]
Es gibt `WrongCredentialsException` aber irgendwie funktioniert sie nicht richtig.

**Comment by alessioC42** [comment]
> ein Passwort ändern Knopf hinzufügen

es gibt schon unten rechts beim Login einen Passwort vergessen Button. Ich würde eher eine "Ausloggen" funktion bei bestimmten Fehlern anbieten. Das Passwort ändern wäre zwar möglich, es ist aber gut möglich, dass das nicht sehr gut funktioniert.

**Comment by kurwjan** [comment]
![image](https://github.com/alessioC42/lanis-mobile/assets/73837560/70f97fb1-e55a-422e-945a-c80156b4dc5a)
![image](https://github.com/alessioC42/lanis-mobile/assets/73837560/a4b881d1-8019-4681-8ecb-56b8cf94f06e)
![image](https://github.com/alessioC42/lanis-mobile/assets/73837560/6fe12d3a-3b28-47fe-8954-78da2dc4f14a)
_Neu anmelden_
