### ISSUE TITLE
Online-Check schlägt bei belastung fehl

### ISSUE THREAD

**Issue by CodeSpoof** [alessioC42/lanis-mobile#212]
wenn man schnell zwischen den Tabs wechselt, wird u.U. angezeigt, man sei offline.

**Comment by alessioC42** [comment]
In diesem Sinne habe ich weniger Probleme mit dem schnellen Tabwechsel als mit "schlechten Verbindungen". Der Server schickt zwar eine Antwort, aber die kommt so spät/langsam, dass der Online-Checker sie nicht wirklich wahrnimmt.

**Comment by alessioC42** [comment]
*nur eine überlegung*
Eventuell könnte man einen dio interceptor schreiben, der den status mit den eigenen anstelle anderer requests ändert. Aktuell wird nur periodisch mit diesem code der online-status überprüft:

```dart
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart';

final connectionChecker = InternetConnection.createInstance(
  customCheckOptions: [
    InternetCheckOption(
      uri: Uri.parse('https://start.schulportal.hessen.de/ajax_login.php'),
    ),
  ],
);
```
Das ist natürlich nicht notwendig, wenn keine Anfragen gestellt werden, und es ist ein wenig unnötige Bandbreite. Als ich das implementiert habe, hat das Schulportal über den Endpoint praktisch einen leeren Body zurückgegeben. Jetzt kommt aus irgendeinem Grund ein HTML-Dokument. Dieser "overload" könnte das Problem verursachen. Wenn zu viele Requests gleichzeitig gesendet werden, dann ist das 3s Limit des Checkers vielleicht einfach zu wenig. Wenn aber stattdessen die "normalen" Requests verwendet werden, dann sollte eine schnellere Antwort erfolgen.
