### ISSUE TITLE
Locale picker

### ISSUE THREAD

**Issue by alessioC42** [alessioC42/lanis-mobile#213]
It should be possible to set the locale introduced in #160 in the settings

**Comment by Rajala1404** [comment]
I added the functionality to pick locales via the System Setting (see #239) but because this only works on Android 13+ this doesn't close this Issue (no idea why GitHub linked the PR to this Issue)

**Comment by alessioC42** [comment]
I haven't tested or reviewed #239 jet, but if it works, there's no need to implement another one. As the countly dashboard reports, about 75% are on Android 13/14 and the percentage is growing. 
![image](https://github.com/user-attachments/assets/a7f429e9-74c4-4c9e-a6d3-45a990c7d43f)
