### ISSUE TITLE
<del>content</del> in Substitutions

### ISSUE THREAD

**Issue by alessioC42** [alessioC42/lanis-mobile#216]
Sukooo hat schon vor längerem mal darauf referiert:

P.S.: Mir ist aufgefallen, dass der Lehrerkürzel manchmal in dem "del" element eingepackt ist, z.B.: <del>Sla</del>.
_Originally posted by @Sukooo in https://github.com/alessioC42/lanis-mobile-autoconfig/issues/1#issuecomment-1927981902_

In https://github.com/alessioC42/lanis-mobile/issues/198 kann man es auch nochmal sehen.

**Comment by Sukooo** [comment]
@alessioC42 

Das zweite, Beispiel:
<del>Bsp</del>

Und mir wäre es egal, wie es angezeigt wird. Wenn du aber eine Linie durchziehen willst, könntest du doch 
```
TextDecoration.lineThrough
```
nutzen?
