### ISSUE TITLE
App doesn't work in School Network with Proxy

### ISSUE THREAD

**Issue by Rajala1404** [alessioC42/lanis-mobile#221]
Steps to reproduce:

1. Connect to School Network (Ethernet or WiFi)  and setup School Proxy (in my case `SchuleGYM` of the Georg-Christoph-Lichtenberg Schule Kassel
2. Try open the App while conneted to this School Network (Android or iOS)
3. Get Error: No Internet connection!

If  a Port or Domains is blocked by the Proxy i can may resolve the issue by unlocking it. But for this i need to know the specific Domain, Port or Protocol or if the App supports Proxy at all

Tested on Android and iOS

**Comment by alessioC42** [comment]
#158 should have fixed this behaviour. Also in the student wifi networks i am familiar with everything works fine.


By calling the url as in here the connection is checked.
https://github.com/alessioC42/lanis-mobile/blob/main/app%2Flib%2Fclient%2Fconnection_checker.dart


Would be interesting to find out, whats different with these networks

**Comment by alessioC42** [comment]
If you have to unlock things you have to enable all domains by the school portal and the "autoconfig" service.

```url
*.schulportal.hessen.de

```

**Comment by Rajala1404** [comment]
Ok with 2.17.2 it still doesn’t work even if the domains are unlocked and also I can connect to the domains just fine I try the new Version now and see if the issue is fixed with the optimized network request

**Comment by alessioC42** [comment]
Yeah. The update was more about Network efficiency and less about compatibility. 

Could you try to make this request with an HTTP rest client:

```http
POST https://start.schulportal.hessen.de/ajax_login.php
```

If the request succeeds with the rest client I see no reason why the app should not. 
What kind of proxy system do you have set up? I may can setup it virtually on my end and reproduce the issue.

**Comment by Rajala1404** [comment]
OK i made a Post Request using curl on an mac with Ethernet and and one on Linux, on the Mac its just succeeds i guess without any code or something and on Linux with Wi-Fi it succeeds and i get the Respond Code 300.

But this How is our Network is build:
We have a WPA2/3 Enterprise Wi-Fi (EAP-PEAP 8021x)
And a HTTP Proxy on Port 8080. On iOS and Android with Automatic Configuration URL.

**Comment by alessioC42** [comment]
> Linux with Wi-Fi it succeeds and i get the Respond Code 300

This is the expected behaviour. It shows, that the school portal is reachable. 

To debug I would not use ADB, but just `flutter run`. I will create a branch with extended network logging. Maybe this could help.

**Comment by Rajala1404** [comment]
I don't now what Software exactly but the proxy domain includes edu.silk-it.de.
Also with adb i don't get any Error Message. I will try with flutter run as you sad but this will take some time because i don't have the Flutter SDK

**Comment by Rajala1404** [comment]
I cant manage to get the Project to compile
`
[rajala1404@archlinux app]$ flutter run
Resolving dependencies... (2.4s)
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_localizations from sdk depends on intl 0.19.0 and sph_plan depends on intl ^0.18.1, flutter_localizations from
  sdk is forbidden.
So, because sph_plan depends on flutter_localizations from sdk, version solving failed.
[rajala1404@archlinux app]$ ls
analysis_options.yaml  app.iml  build     fonts  l10n.yaml  linux  pubspec.yaml  test  windows
android                assets   build.sh  ios    lib        macos  README.md     web
[rajala1404@archlinux app]$ nao pubspec.yaml 
bash: nao: command not found
[rajala1404@archlinux app]$ vim pubspec.yaml 
[rajala1404@archlinux app]$ flutter create .
Recreating project ....
Resolving dependencies... (4.5s)
Downloading packages... (14.5s)
Got dependencies.
Wrote 3 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.

[rajala1404@archlinux app]$ flutter run
Launching lib/main.dart on Linux in debug mode...
ERROR: ../../../.pub-cache/hosted/pub.dev/chips_input-0.1.0/lib/chips_input.dart:603:25: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
ERROR:  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../.cache/flutter_sdk/packages/flutter/lib/src/material/text_theme.dart').
ERROR: Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
ERROR:         theme.textTheme.subtitle1!.copyWith(height: 1.5).merge(widget.style);
ERROR:                         ^^^^^^^^^
ERROR: Target kernel_snapshot failed: Exception
Building Linux application...                                           
Error: Build process failed
`

**Comment by CodeSpoof** [comment]
The repository is made and ised with Android Studio and the Flutter Plugin. Try debugging with those. Build and installation parameters should be set automatically using those.

**Comment by alessioC42** [comment]
I do not think thats the point where it fails. The code handels android and IOS so if it is ran on linux it should just leave out platform specific code like push notifications etc. 

Maybe a dependency upgrade (or downgrade) of `flutter_localizations` is necessary. I had this issue yesterday after upgrading flutter but had no time to investigate

**Comment by alessioC42** [comment]
Maybe going back one release can fix the issue

**Comment by alessioC42** [comment]
The [chips_input](https://github.com/zsoerenm/chips_input/) Plugin we where using is not really compatible with the latest Flutter release 3.22. I also encounter a lot of other issues with this new release. I managed to get it in a debugable state on the branch `no-chips-input`, but only with flutter version 3.19 so you may have to run `flutter downgrade` before running `flutter run`.

**Comment by Rajala1404** [comment]
Oh ok. I tried before with downgraded Flutter and then it worked but i can try next week with this

**Comment by alessioC42** [comment]
Did you manage to configure your network with the logs of the app? Can I close the issue?

**Comment by Rajala1404** [comment]
I'm currently on it but i cant get the App to Compile in Android Studio at all i just No Device Found Error (
`No connected devices found; please connect a device, or see flutter.dev/setup for getting started instructions.`) But if i try it via CLI i don't get this Error i only get the Error that Gradle Timed Out i suspect because of the Proxy. 
I try it now with a School Mac that is connected via Ethernet

**Comment by Rajala1404** [comment]
Now on a Mac i could get it to Compile but it sill doesn't work and it looks like it fails at:
Future<void> performBackgroundFetch()
```
I/flutter (29202): │ #0   performBackgroundFetch (package:sph_plan/background_service.dart:71:12)
I/flutter (29202): │ #1   <asynchronous suspension>
I/flutter (29202): │ 
I/flutter (29202): │ ⚠️ Error occurred in background service
```
In Future<bool> testConnection()
```
Future<bool> testConnection() async {
    try {
      await dio.post("https://start.schulportal.hessen.de/ajax_login.php");
      status = ConnectionStatus.connected;
      return true;
    } catch (e) {
      status = ConnectionStatus.disconnected;
      return false;
    }
  }
```

But i tested on the Android Phone and on the Mac and Linux but the Post Request Succeeds so I think its only in this App that it doesnt work

**Comment by alessioC42** [comment]
Can you provide the output when modifying the `testConnection` method as follows:

```dart
//place at top of file
import 'package:flutter/material.dart';


Future<bool> testConnection() async {
    try {
      await dio.post("https://start.schulportal.hessen.de/ajax_login.php");
      status = ConnectionStatus.connected;
      return true;
    } catch (e, stack) {
      debugPrint(e.toString());
      debugPrintStack(stackTrace: stack);
      status = ConnectionStatus.disconnected;
      return false;
    }
  }
```

**Comment by Rajala1404** [comment]
Yeah but i can do that maybe next Week (if I don't get it to compile on my Notebook)

**Comment by alessioC42** [comment]
Maybe interesting, but I have to take a deeper look some time:

https://pub.dev/packages/platform_proxy

**Comment by Rajala1404** [comment]
Here is the Error if i modify the code as you said. It looks like it can't established an connection and also it takes very long before it fails.

```
I/flutter ( 4782): DioException [connection error]: The connection errored: Connection failed This indicates an error which most likely cannot be solved by the library.
I/flutter ( 4782): Error: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = start.schulportal.hessen.de, port = 443
I/flutter ( 4782): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509:7)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #1      CustomConnectionChecker.testConnection (package:sph_plan/client/connection_checker.dart:46:7)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #2      CustomConnectionChecker._isConnected (package:sph_plan/client/connection_checker.dart:32:7)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #3      CustomConnectionChecker.connected (package:sph_plan/client/connection_checker.dart:37:39)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #4      SPHclient.login (package:sph_plan/client/client.dart:128:11)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #5      performBackgroundFetch (package:sph_plan/background_service.dart:35:5)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #6      callbackDispatcher.<anonymous closure> (package:sph_plan/background_service.dart:18:7)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:42)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581:22)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 4782): │ #0   performBackgroundFetch (package:sph_plan/background_service.dart:71:12)
I/flutter ( 4782): │ #1   <asynchronous suspension>
I/flutter ( 4782): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 4782): │ ⚠️ Error occurred in background service
I/flutter ( 4782): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 4782): DioException [connection error]: The connection errored: Connection failed This indicates an error which most likely cannot be solved by the library.
I/flutter ( 4782): Error: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = start.schulportal.hessen.de, port = 443
I/flutter ( 4782): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509:7)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #1      CustomConnectionChecker.testConnection (package:sph_plan/client/connection_checker.dart:46:7)
I/flutter ( 4782): <asynchronous suspension>
I/NotificationManager( 4782): io.github.alessioc42.sph: notify(-566180318, null, Notification(channel=WorkmanagerDebugChannelId shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)) as user
I/WM-WorkerWrapper( 4782): Worker result SUCCESS for Work [ id=35e8ef2b-73e1-4b5a-92e6-2e829ed8876b, tags={ dev.fluttercommunity.workmanager.BackgroundWorker } ]
I/flutter ( 4782): DioException [connection error]: The connection errored: Connection failed This indicates an error which most likely cannot be solved by the library.
I/flutter ( 4782): Error: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = start.schulportal.hessen.de, port = 443
I/flutter ( 4782): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509:7)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #1      CustomConnectionChecker.testConnection (package:sph_plan/client/connection_checker.dart:46:7)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #2      CustomConnectionChecker._isConnected (package:sph_plan/client/connection_checker.dart:32:7)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #3      CustomConnectionChecker.connected (package:sph_plan/client/connection_checker.dart:37:39)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #4      SPHclient.login (package:sph_plan/client/client.dart:128:11)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #5      _StartupScreenState.performLogin (package:sph_plan/startup.dart:77:7)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): DioException [connection error]: The connection errored: Connection failed This indicates an error which most likely cannot be solved by the library.
I/flutter ( 4782): Error: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = start.schulportal.hessen.de, port = 443
I/flutter ( 4782): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509:7)
I/flutter ( 4782): <asynchronous suspension>
I/flutter ( 4782): #1      CustomConnectionChecker.testConnection (package:sph_plan/client/connection_checker.dart:46:7)
I/flutter ( 4782): <asynchronous suspension>
```
