### ISSUE TITLE
Das erstellen von Filtern funktioniert nicht mehr.

### ISSUE THREAD

**Issue by ItsFrocat** [alessioC42/lanis-mobile#233]
Wenn man einen Filter in das Textfeld tippt und dann auf "[dein filter] hinzufügen" drückt, passiert nichts und kein Filter wird hinzugefügt. In einer früheren Version hatte das nicht funktioniert, jetzt allerdings nicht mehr.

**Comment by alessioC42** [comment]
Hey, könntest du eine Bildschirmaufnahme von dem Bug machen? Ich kann es mit der aktuellen Version (2.18.1) nicht reproduzieren.

**Comment by ItsFrocat** [comment]
Kann leider an meinem Handy keine Bildchirmaufnahme direkt machen, weil ich noch Android 10 habe. Habe stattdessen meinen Bildschirm an meinen Computer geteilt, ist deswegen ein bisschen schlechte Qualität.

https://github.com/alessioC42/lanis-mobile/assets/65976911/189351e5-1c1a-4a0c-a897-fefb7da3c35d

**Comment by kurwjan** [comment]
Das habe ich gar nicht erwartet. `flutter_tagging_plus` sollte eigentlich mit Android 10 und auf Countly habe leider kein Crash Report gefunden.

**Comment by alessioC42** [comment]
Ich kann es ebenfalls mit den infos nicht reproduzieren. Ich habe auch noch nie von Fehlern dergleichen gehört. (und die Leute auf meiner Schule spamen mich praktisch voll, wenn sie einen Fehler finden)

Ich würde vorschlagen, dass du die App neu installierst. Mit einem Datenverlust ist das ja nicht verbunden, weil alles über das Netzwerk geladen wird. 

Meine Theorie ist, dass es irgendwas mit der "automatisch festlegen" Funktion und einem custom Server zu tun hat, konnte aber diesbezüglich auch erstmal nichts machen. Ich schaue es mir die nächsten Tage nochmal an.

**Comment by ItsFrocat** [comment]
ich habe die App jetzt neu installiert und mein Handy neu gestartet, aber es funktioniert immer noch nicht. Ich habe jetzt alle Versionen getestet ab denen die ich benutzt habe und die letzte Version auf der es noch funktioniert ist 2.17.3.

**Comment by alessioC42** [comment]
Interessanterweise tritt der Fehler auch bei mir auf, seit ich meine Custom ROM neu installiert habe. Ich sollte ihn also reproduzieren und beheben können.

**Comment by ItsFrocat** [comment]
Bei mir funktioniert es komischerweise wieder ohne Probleme Filter zu erstellen.

**Comment by alessioC42** [comment]
Ich werde versuchen heute ein update zu pushen. Es nervt mich selber auch extremst.
