### ISSUE TITLE
Ipad

### ISSUE THREAD

**Issue by meep-beep** [alessioC42/lanis-mobile#238]
Warum kann man die App nicht auf dem Ipad herunterladen?

**Comment by alessioC42** [comment]
Ich arbeite gerade daran, die app für iOS und iPadOS zugänglich zu machen. 

Du kannst beta zugang für iOS erhalten, wenn du mir deine Apple-ID Mail an alessioc42.dev@gmail.com sendest.

**Comment by alessioC42** [comment]
You can also join via Testflight here: https://testflight.apple.com/join/THSFD13a
