### ISSUE TITLE
Apple or Google Wallet

### ISSUE THREAD

**Issue by bemerkbarGrafik** [alessioC42/lanis-mobile#242]
Adding the support with Apple or Google Wallet, incase they forget to bring their School cards with them.

**Comment by alessioC42** [comment]
Hi, das wäre erstmal eine gute Idee ist aber technisch schlicht nicht/schlecht Umsetzbar. Die Wallet Anwendungen funktionieren, indem sie den NFC chip einer Karte spoofen. 
Soweit ich weiß, gibt es keine einheitlichen Schülerausweise in Hessen und schon garnicht welche mit NFC. An unserer Schule ist ein simpler Barcode auf der Rückseite (prinzipiel einfach eine Zahl), der mit Barcode Scanner bei bedarf gescannt wird. 

Jetzt könnte man einen Barcode Scanner (Kamera) verwenden, um einen solchen Barcode zu lesen und anschließend anzuzeigen, jedoch tut ein Bild des Schülerausweises praktisch genau das selbe. Gibt es bei euch spezielle Schülerausweise?

**Comment by alessioC42** [comment]
Was auch recht interessant sein könnte ist die Mögliche [Littera-verknüpfung](https://info.schulportal.hessen.de/tag/littera-lm/) im Schulportal. Bei uns zumindest, laufen die Schülerausweise mehr oder weniger über littera. Wenn die Integration irgendwann kommen sollte stünde dem Anzeigen seiner eigenen ID ( der barcode auf dem Schülerauseis) wenig entgegen.

**Comment by bemerkbarGrafik** [comment]
Okay Danke schön
