### ISSUE TITLE
Bessere UI/UX

### ISSUE THREAD

**Issue by kurwjan** [alessioC42/lanis-mobile#40]
## Bessere UI/UX

Das braucht auf jeden Fall bisschen länger, aber man kann einzelne Commits in Main bringen.

## Ziel

Eine einheitliche _(const vars für Padding und so weiter, damit jede Seite egal welcher Entwickler gleich aussieht und aufgebaut ist)_, schöne _(und funktionelle)_ und einfach benutzbare UI, die jeder verstehen sollte.

### Aktuelle Ideen

**Material 3 Guidelines: https://m3.material.io/**
**Animationen pub package: https://pub.dev/packages/animations** _(Hat auch Material Motion)_

**Illustrations?: https://undraw.co/illustrations**

- Error page (besonders wichtig für Bug reporting)
- Alle (Übersichts-)daten beim Einloggen preloaden mit StreamBuilder und Streams *(ähnlich wie Nachrichten Support aufgebaut ist)*
    - Man kann auswählen ob man alles preloaden will für eine smoothe Experience oder nur Vp um so schnell wie möglich enttäuscht zu sein.
     - Somit hat man auch ein Cache der alle  15min oder länger reloaded (Vorgeschlagen von @Sukooo)
- Einrichtungsassistent
- Besserer Login
- Drawer ersetzen mit Material 3 NavigationDrawer
   - Erster Widget: Schulhintergrund mit Schülerfoto und Name, und Name der Schule
- Embedded Webview anstatt Browser zu öffnen
- ~_Bottom Navbar? Nur als Favoritenleiste, Hauptleiste?_~
- Animationen und Transitions nach Material Motion
- Mehr Material-3-Compliance _(Zb. einheitliches Padding in 4dp Schritte)_
- Material You Support
- ~Support für größere Bildschirme nach Material Guidelines~ -> Verschoben
     - Tablets priorisieren

### Mögliche Ideen _(die auch villt. verschoben werden)_

- Zeige was neu ist in der neuen Version und überprüfe ob es die neuste Version ist.
- Flutter Spinkit als Easter Egg Option oder so, weil wieso nicht
- Introduction nach ersten einloggen
- Jede App hat ein Info-Knopf, um zu zeigen was die einzelnen Elemente bedeuten, wäre ähnlich zu Introduction.
- Personalisierte Overview page _(Aber man kann auswählen ob man Vertretungsplan oder Overview zuerst sehen möchte)_
- Personalisierte Vertretungsplan page

### Nein
- Desktop support
  - Lanis Website ist auf dem PC gut und benutzt man weniger als auf dem handy

### Gepushte Ideen

- Neuer Drawer und Login (#47)
- BottomBar Favoritenleiste (#49)
- Cache und vorher laden von Daten (#59)
- Error widget (#87)
- Calendar refresh (#88)
- Nachrichten verbessern und formatieren (#89)
- Besser login / Setup screen hinzufügen (#95)
- Mein Unterricht verbessern (#98)
- Neue Farbeinstellungen (#103)

### Aktuelle To-Dos für @kurwjan 

- [x] Daten cachen (und vorher laden, wenn man's will)
- [x] Error page

- [x] UI mit zu viel Density erneuern
   - VP: _Fertig_ TODO: Simplify
   - Nachrichten: _Fertig_
   - Mein Unterricht: _Fertig_
   - Kalendar: _Fertig_
   - Ziel: freundlichere UI, auch wenn es heißt nicht effizient die Bildschirmgröße zu benutzen
- [x] "Einrichtungsassistent" am Anfang

- [x] Material You und andere Farbeinstellungen
   - https://pub.dev/packages/dynamic_color

- [x] Größere Displays unterstützten
  - Nicht einfach scalen mit Displaygröße sondern z.B. mehr Cards oder Listtiles gleichzeitig zeigen und wenn es geht mehr Infos "direkt" zeigen, das heißt Sachen die man erst mit einen Klick darauf sehen kann, könnte man direkt in der Overview Page sehen.

- [ ] Animation
   - Erst machen wenn UI irgendwie finalisiert ist.

**Comment by alessioC42** [comment]
> * Desktop auch supporten _(Flatpak muss kommen, bei AUR wird es wahrscheinlich nicht erlaubt)_

Das wäre erst mal ein größerer Krampf. Die meisten Module die ich benutze sind android/ios only. Für Desktop würde ich ein ganz neues Projekt mit Electron machen. Das ist zumindest meiner Meinung nach besser geeignet.

**Comment by kurwjan** [comment]
Bisher habe ich nur gesehen, dass nur die Benachrichtigungen auf Android laufen, kann sein das ich mich auch täusche. Glaube ein ganz neues Projekt zu machen wäre auch zu viel.

**Comment by kurwjan** [comment]
Daten cachen sollte fast ready sein

**Comment by alessioC42** [comment]
outdated
