### ISSUE TITLE
App Bug

### ISSUE THREAD

**Issue by baum-eule** [alessioC42/lanis-mobile#66]
Wenn ich mit meinem Account über die App anmelde hat es keine Probleme, aber danach ist nur noch Hellgrau zu sehen.
(Es könnte daran liegen, dass meine Schule keinen Vertretungsplan beim Schulportal hat.)
Die Version v2.8.0+8 hat den Bug aber die Version v2.7.0+7 hat ihn nicht.

**Comment by alessioC42** [comment]
Moin,
du bist schon der Zweite, der auf das Problem aufmerksam macht. Die Ursache wurde gefunden und wird mit dem nächsten Update (warscheinlich Morgen oder Übermorgen) behoben. (siehe #60)
LG

**Comment by baum-eule** [comment]
Danke

**Comment by kurwjan** [comment]
den grauen screen müsste ich mal auch endlich durch einen richtigen error builder ersetzen
