### ISSUE TITLE
den grauen screen müsste ich mal auch endlich durch einen richtigen error builder ersetzen

### ISSUE THREAD

**Issue by alessioC42** [alessioC42/lanis-mobile#67]
den grauen screen müsste ich mal auch endlich durch einen richtigen error builder ersetzen

_Originally posted by @kurwjan in https://github.com/alessioC42/lanis-mobile/issues/66#issuecomment-1862911968_

**Comment by alessioC42** [comment]
Du hast dich freiwillig gemeldet? xD

**Comment by kurwjan** [comment]
Wird nach Vp Tabs gemacht
