### ISSUE TITLE
Proprietary components

### ISSUE THREAD

**Issue by IzzySoft** [alessioC42/lanis-mobile#69]
Looks like your latest release comes with several proprietary components:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeComp,Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Installations (/com/google/firebase/installations): NonFreeNet
* FlutterFire (/io/flutter/plugins/firebase): NonFreeNet

6 offenders.
```

which means I'd have to remove it from my repo – as this exceeds the number of "tolerated offenders". But maybe you can provide an alternative build flavor (and attach its corresponding APK to your releases) which comes without those? You'd need that for your listing with F-Droid anyway. So effective with the next sync (around 7 pm UTC) your app will carry 3 AntiFeatures in my repo (as outlined in above "code quote") instead, in the hope of such a flavor becoming available soon.

**Comment by alessioC42** [comment]
Yes, that is the plan. Crashlytics is not necessary for the app to run, but it is very necessary for the development, as it is an app for a reverse-engineered website with SSR. I will be adding a "non-crashlytics" build soon.

**Comment by IzzySoft** [comment]
And in the long run you might evaluate a (self-hosted) Sentry I've heard. LK already linked you to my snippet for that. Glad to read, so my decision to keep it up was right. Though I was considering just to switch back to the previous release and disable updates until solved. Might have been better, so nobody gets Crashlytics in "by accident" and feel annoyed…

Please give me a ping then when the new variant is available, and let me know what naming patterns you intend to keep the two apart – so I can tell my updater which one to grab and which one to ignore. Wish you easy implementation of that!

**Comment by alessioC42** [comment]
@IzzySoft 
As you already saw on the Gitlab RFP issue I am changing to an self hosted version of Countly, since my server is not able to handle an Sentry instance. Naming conversion will stay the same.

**Comment by IzzySoft** [comment]
Will Countly be opt-in – or is it enabled by default? I see Crashlytics is gone with the latest release, congrats! GMS and Firebase are still there. Overlooked – or is there a reason they must remain?

**Comment by alessioC42** [comment]
Countly is enabled by default in the application.
GMS and Firebase are still there?
I think the Countly SDK might be the problem. ([doc](https://support.count.ly/hc/en-us/articles/4409295642137-Flutter-20-11-0-#h_01HBFXQ9JG0DV0580V79R8EJGE));
Apparently Countly also supports push notifications via Firebase and GMS. I do not use these features in my application and would like to remove them if possible. I am not sure if this is possible with the Countly SDK yet. I will have to check tomorrow.

**Comment by IzzySoft** [comment]
Ah, I see – yeah, I was suspecting something along those lines but wasn't sure what library it might be. There might be some tricks along [these lines](https://gitlab.com/-/snippets/1896503#push), using gradle's `excludeGroup`, but not being an Android dev myself I cannot tell.

**Comment by alessioC42** [comment]
I think opt-in is coming. Should be easy to implement.

I have no idea how Gradle works. I have to find out. But I think it should be possible too.

**Comment by IzzySoft** [comment]
> I think opt-in is coming. Should be easy to implement.

I guess so. Once it's there in a new release, please let me know and I drop the `Tracking` AF.

As for the other part: :crossed_fingers:

**Comment by alessioC42** [comment]
It turns out that Countly has a Flutter SDK without GMS and Firebase. On pub.dev it is listed way below the normal package list, and I did not find anything about it in the docs. Long story short: GMS and Firebase are out.

Also Countly is now opt-in.

I guess since Countly is also not in your snippet as "approved" that I leave the issue closed for the Gitlab RFP repo?

Another question just out of interest: How did you find the project? Do you have a web crawler that lists potential projects for you, or did someone contact you?

**Comment by IzzySoft** [comment]
Confirming all offenders gone – anti-features are removed (effective with the next sync in less than an hour), thanks & congrats!

Snippet updated as suggested: Countly now is in the "approved" section with a footnote for the details.

> Do you have a web crawler that lists potential projects for you

![image](https://github.com/alessioC42/lanis-mobile/assets/6781438/2790d99c-3a10-4183-8be8-076761e4ef3e)

Also one for GitLab and one for Codeberg. And there's always [my issue tracker](https://gitlab.com/IzzyOnDroid/repo/-/issues/) where people can suggest apps to be included. Those who cannot do so on GitLab sometimes send me suggestions via mail or DM to [my Fediverse account at floss.social](https://floss.social/@IzzyOnDroid).

**Comment by alessioC42** [comment]
This is a pretty cool tool.

> **Edit:** you might wish to mention the opt-in with the app description in the "Data protection" ("Datenschutz") section.

Gonna do that.

Thanks for your help!
