### ISSUE TITLE
F-Droid Idee

### ISSUE THREAD

**Issue by baum-eule** [alessioC42/lanis-mobile#71]
Wäre es möglich die App bei F Droid ein zu reichen und verfügbar zu machen?

**Comment by alessioC42** [comment]
F-Droid support is done via the repo from Izzy. 
Then you just have to link the repo in F-Droid. 

https://apt.izzysoft.de/fdroid/
(It might take a while until v2.10 is available)

see also [here](https://gitlab.com/fdroid/rfp/-/issues/2603)
