### ISSUE TITLE
Text Formatierung

### ISSUE THREAD

**Issue by baum-eule** [alessioC42/lanis-mobile#75]
Text in "Nachrichten"  und "Mein Unterricht" kann Formatiert werden und dies wird nicht angezeigt in der app.
https://support.schulportal.hessen.de/knowledgebase.php?article=664

**Comment by kurwjan** [comment]
Werde ich einfach zusammen mit den Interagier-PRs () der jeweiligen App pushen

**Comment by kurwjan** [comment]
Bei Nachrichten wäre das einfach, weil dort gibt es eine API und dort sollte der Lanis Syntax drinne sein, aber bei Mein Unterricht gibt es keine API, somit ist es bisschen schwieriger (oder eher ekliger) es rauszuparsen. Das Ding ist auch, kein Lehrer benutzt diesen Lanis Syntax (außer villt `- `), somit weiß ich nicht wie der HTML Code zu diesem Lanis Syntax genau aussieht.

**Comment by kurwjan** [comment]
Hab gerade gesehen bei Nachrichten (per API) wird auch nicht der Text mit Lanis Syntax zurück gegeben.
Zb.: Aufzählungen werden so zurück gegeben: `•	`. Jetzt weiß ich nicht wie es mit Fett, Kursiv und so aussieht. Außerdem wird auch teilweise HTML Code zurück gegeben, zB.: `<br>`. Glaube ich verschiebe dieses Issue in die Zukunft, da ich noch nicht weiß wie der zurück gegebene Syntax aussieht.

**Comment by baum-eule** [comment]
Könnte man es hier nicht sehen?
https://support.schulportal.hessen.de/knowledgebase.php?article=664

**Comment by kurwjan** [comment]
Für Mein Unterricht glaub schon

**Comment by kurwjan** [comment]
Auf der Seite ist fett <strong> und auf Mein Unterricht <b>

**Comment by baum-eule** [comment]
Und bei den Nachrichten kann man es selbst testen.
![image](https://github.com/alessioC42/lanis-mobile/assets/130868748/c1176cf0-a583-4163-9108-f571fd9a5a77)

**Comment by kurwjan** [comment]
woher hast du das?

**Comment by baum-eule** [comment]
Man kann in Nachrichten Lehrern schreiben und ich habe einfach zum Test einem Lehrer geschrieben, der nicht mehr auf der Schule ist. (Die alten Lehrer können auch ein Fehler meiner Schule sein) Und dort hat es funktioniert.

**Comment by kurwjan** [comment]
Bei Nachrichten ist alles genauso wie von Lanis angegeben, außer bei Aufzählungen gibt es manchmal Anomalien.
Bei Mein Unterricht ist es halt schlecht gerade einen Lehrer zu fragen, da sie einen ghosten werden über die Ferien.

**Comment by baum-eule** [comment]
Bei Mein Unterricht kann ich die vielleicht die Daten liefern.

**Comment by kurwjan** [comment]
Das wäre schön

**Comment by baum-eule** [comment]
wäre das ein guter Test Text?

fett wird zu *fett**
unterstrichen wird zu __unterstrichen__
entfernt wird zu --entfernt--
- Aufzählung 1
- Aufzählung 2
- Aufzählung 3
Quellcode wird zu `Quellcode`
Datum v1  12.04.2018 
Datum v1  12.04.18
Datum v2  (12.04.2018) 
Datum v2  (12.04.18)
Uhrzeitenangabe 11:13
Link https://example.com/
Linkkürzung https://example.com/abcdefghijklmnopqrstuvwxyz_abcdefghijklmnopqrstuvwxyz_abcdefghijklmnopqrstuvwxyz
Email test@example.com
Zahl sonderfall v1 _1
Zahlen sonderfall v1 _(123)
Zahl sonderfall v2 ^1
Zahlen sonderfall v2 ^(123)

**Comment by kurwjan** [comment]
Ja

**Comment by baum-eule** [comment]
Hatte noch einen Fehler gefunden wenn man den Text bei Nachrichten abschickt und habe etwas hinzufügt und schreibe es einem Lahrer.

```
fett wird zu *fett**
unterstrichen wird zu __unterstrichen__
entfernt wird zu --entfernt--
- Aufzählung 1
- Aufzählung 2
- Aufzählung 3
Quellcode wird zu `Quellcode`
Datum v1  12.04.2018 
Datum v1  12.04.18
Datum v2  (12.04.2018) 
Datum v2  (12.04.18)
Uhrzeitenangabe 11:13
Link https://example.com/
Linkkürzung https://example.com/abcdefghijklmnopqrstuvwxyz_abcdefghijklmnopqrstuvwxyz_abcdefghijklmnopqrstuvwxyz
Email test@example.com
Zahl sonderfall v1 _1
Zahl sonderfall v1 _(1)
Zahlen sonderfall v1 _(123)
Zahl sonderfall v2 ^1
Zahl sonderfall v2 ^(1)
Zahlen sonderfall v2 ^(123)
```

**Comment by alessioC42** [comment]
Alles, was in einer "markup" Klasse ist, wird so dargestellt. Dafür ist das Script auf 
https://start.schulportal.hessen.de/js/markup.js
zuständig.
Wenn man das einfach Kopieren würde, und dann den HTML code irgendwie anzeigt (glaube das geht nativ recht gut), dann sollte es super funktionieren

**Comment by alessioC42** [comment]
> Hab gerade gesehen bei Nachrichten (per API) wird auch nicht der Text mit Lanis Syntax zurück gegeben.
> Zb.: Aufzählungen werden so zurück gegeben: `• `. Jetzt weiß ich nicht wie es mit Fett, Kursiv und so aussieht. Außerdem wird auch teilweise HTML Code zurück gegeben, zB.: `<br>`. Glaube ich verschiebe dieses Issue in die Zukunft, da ich noch nicht weiß wie der zurück gegebene Syntax aussieht.

Das klingt stark nach SSR (server side rendering), wenn da eine "markup" Klasse in dem HTML code ist, dann wäre ich stark verwundert. Zumindest ist es in meinen "Mein Unterricht" fällen so, dass es zwar `<br>`'s gibt, aber keine `• ` und das das JS script macht.

**Comment by kurwjan** [comment]
> Alles, was in einer "markup" Klasse ist, wird so dargestellt. Dafür ist das Script auf https://start.schulportal.hessen.de/js/markup.js zuständig. Wenn man das einfach Kopieren würde, und dann den HTML code irgendwie anzeigt (glaube das geht nativ recht gut), dann sollte es super funktionieren

Dann ist das mit Mein Unterricht wohl geklärt. Das mache ich dann ganz am Ende nach #40 und setup screen.

**Comment by alessioC42** [comment]
closed by #89
