### ISSUE TITLE
Name "lanis-mobile"

### ISSUE THREAD

**Issue by jpospi** [alessioC42/lanis-mobile#76]
Warum die Umbenennung? Der Name LANiS ist veraltet.

**Comment by alessioC42** [comment]
Es gab 3 Hauptgründe für die Umbenennung:

1: (eigentlich unbedeutend) Das alte App-Icon war Müll, den ich mit GIMP in 3 Minuten zusammengeklickt habe.
2: Der Name "SPH Vertretungsplan" passt nicht mehr, da jetzt auch Kalender, Nachrichten und Mein Unterricht unterstützt werden.
3: Der Name Lanis hat sich unter den SPH-Benutzern etabliert. Wenn ich jemanden aus meiner Klasse frage, was SPH bedeutet, hat er keinen Plan. Wenn ich nach Lanis frage, weiß die Person, dass es etwas mit dem IT-System der Schule zu tun hat.

**Comment by jpospi** [comment]
Danke für die Antwort und deine Arbeit hier!
Die Bezeichnungen variieren von Schule zu Schule. Bei uns kann mit Lanis niemand etwas anfangen.
Die meisten Lanis Domains sind inzwischen deaktiviert.
