### ISSUE TITLE
Bei den Einträgen von "Mein Unterricht"  Inhalt und  Hausaufgaben klar Kennzeichen

### ISSUE THREAD

**Issue by baum-eule** [alessioC42/lanis-mobile#86]
In der App werden zurzeit wird der Inhalt ("Das haben wir heute gemacht ...") nicht von Hausaufgaben getrennt, wenn beides in einem Eintrag ist.

**Comment by kurwjan** [comment]
Bisher ist das einfach nur das Mein Unterricht Applet umgesetzt, als eine eigene Seite, finde ok das noch der Inhalt so gezeigt wird.

**Comment by kurwjan** [comment]
Sehe gerade manchmal ist der Inhalt dupliziert.

**Comment by baum-eule** [comment]
ja das meine ich es kann auch so aussehen
![image](https://github.com/alessioC42/lanis-mobile/assets/130868748/544a5ed8-822f-4aab-8566-6c0397d45133)
dann ist es nicht dupliziert

**Comment by kurwjan** [comment]
![image](https://github.com/alessioC42/lanis-mobile/assets/73837560/d89333ce-9c3e-4893-ae49-bdffe25e519e)

Was ist die richtige "Hausaufgabe", das was oben steht oder unten?

**Comment by alessioC42** [comment]
Ich habe den parser für die stelle geschrieben. Ich ändere das heute oder morgen.

**Comment by baum-eule** [comment]
> ![image](https://private-user-images.githubusercontent.com/73837560/292467393-d89333ce-9c3e-4893-ae49-bdffe25e519e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDI1NDgsIm5iZiI6MTcwMzI0MjI0OCwicGF0aCI6Ii83MzgzNzU2MC8yOTI0NjczOTMtZDg5MzMzY2UtOWMzZS00ODkzLWFlNDktYmRmZmUyNWU1MTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwNTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YjQ0MDg4ZGFmMmNkOTE3YjFjYjRlN2FmYjUyMTNjYmQxZDJkMjIwYmU2ZWUxM2JkMDgyNzI5ZjQwZjNlOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.74tX35-4hpVEQWogziG-JmUpmGnazCwkUNzBAc70xl8)
> 
> Was ist die richtige "Hausaufgabe", das was oben steht oder unten?
> 
> ja unten

![image](https://github.com/alessioC42/lanis-mobile/assets/130868748/0962045f-aafb-4119-ad36-07430e8adbe5)

**Comment by alessioC42** [comment]
> Sehe gerade manchmal ist der Inhalt dupliziert. ![image](https://private-user-images.githubusercontent.com/73837560/292465858-26abb54e-f0f2-42dd-81a5-5931d41b2a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDcyNDUsIm5iZiI6MTcwMzI0Njk0NSwicGF0aCI6Ii83MzgzNzU2MC8yOTI0NjU4NTgtMjZhYmI1NGUtZjBmMi00MmRkLTgxYTUtNTkzMWQ0MWIyYTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEyMDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NDI0YmE1NzJkY2NjNDdjMDg0Nzk0Nzg2NTM1NzA1MzkwYmY3M2EzMzllZDNkNzU0ZTQ2ZTNhOTM3ZjIyN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KGhry6g8jiz2duBHLfrXNbStwcyDt16ySQ1QAY_4uU0)
> 
> Villt. könnte man irgendwann bei einer Overview Page oder so nur Hausaufgaben anzeigen


Das mit dem Duplizieren kann nur ein Lehrer sein, der einen Eintrag in ein anderes Textfeld kopiert.
Die Übersichtsseite ist im Moment sehr hypothetisch, da sie viel Netzwerkarbeit erfordern würde. Zuerst müssen die Apps an sich funktionieren und dann kann man über Erweiterungen nachdenken. @kurwjan: Mach auch eins nach dem anderen. Es ist schwierig für mich, Dinge zu tun, wenn du an mehreren Baustellen gleichzeitig arbeitest. Im Moment machst du, soweit ich weiß, den Vertretungsplan und jetzt anscheinend noch meinen Unterricht.

**Comment by alessioC42** [comment]
> Ich habe den parser für die stelle geschrieben. Ich ändere das heute oder morgen.

Nvm, keiner meiner Lehrer hat irgendwas reingestellt.

**Comment by kurwjan** [comment]
wurd gemacht mit #98
